services:
  backend:
    build: ./back
    container_name: mern_backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/todos_db
    depends_on:
      - mongo

  frontend:
    build: ./front
    container_name: mern_frontend
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mern_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  nginx:
    build: ./nginx
    container_name: mern_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
